import { Category } from '../../types';
import { categoryColors } from '../../theme';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat_food',
    name: 'Food & Dining',
    icon: 'utensils',
    color: categoryColors[0],
    type: 'expense',
    isCustom: false,
    keywords: [
      'swiggy', 'zomato', 'restaurant', 'cafe', 'coffee', 'mcdonalds',
      'dominos', 'pizza', 'burger', 'kfc', 'subway', 'starbucks',
      'food', 'dining', 'eat', 'meal', 'lunch', 'dinner', 'breakfast',
      'biryani', 'dosa', 'thali', 'hotel', 'dhaba', 'bakery',
      'dunkin', 'baskin', 'ice cream', 'dessert', 'snack',
    ],
    parentId: null,
    sortOrder: 0,
  },
  {
    id: 'cat_groceries',
    name: 'Groceries',
    icon: 'shopping-cart',
    color: categoryColors[1],
    type: 'expense',
    isCustom: false,
    keywords: [
      'bigbasket', 'blinkit', 'zepto', 'dmart', 'grocery', 'supermarket',
      'reliance', 'fresh', 'vegetables', 'fruits', 'provision',
      'kirana', 'store', 'market', 'organic', 'instamart', 'jiomart',
      'walmart', 'costco', 'kroger', 'whole foods', 'trader joe',
    ],
    parentId: null,
    sortOrder: 1,
  },
  {
    id: 'cat_transport',
    name: 'Transport',
    icon: 'car',
    color: categoryColors[2],
    type: 'expense',
    isCustom: false,
    keywords: [
      'uber', 'ola', 'rapido', 'fuel', 'petrol', 'diesel', 'metro',
      'bus', 'train', 'cab', 'taxi', 'auto', 'parking', 'toll',
      'lyft', 'gas', 'shell', 'hp petrol', 'indian oil', 'bharat petroleum',
      'irctc', 'railway', 'flight', 'airline', 'indigo', 'spicejet',
    ],
    parentId: null,
    sortOrder: 2,
  },
  {
    id: 'cat_housing',
    name: 'Housing',
    icon: 'home',
    color: categoryColors[3],
    type: 'expense',
    isCustom: false,
    keywords: [
      'rent', 'maintenance', 'society', 'electricity', 'gas bill',
      'water bill', 'property', 'emi', 'mortgage', 'home loan',
      'apartment', 'flat', 'house', 'plumber', 'electrician',
      'repair', 'paint', 'furniture', 'ikea', 'urban ladder',
    ],
    parentId: null,
    sortOrder: 3,
  },
  {
    id: 'cat_shopping',
    name: 'Shopping',
    icon: 'shopping-bag',
    color: categoryColors[4],
    type: 'expense',
    isCustom: false,
    keywords: [
      'amazon', 'flipkart', 'myntra', 'ajio', 'mall', 'fashion',
      'clothes', 'shoes', 'watch', 'jewelry', 'electronics',
      'nykaa', 'meesho', 'snapdeal', 'ebay', 'target', 'nike',
      'adidas', 'puma', 'h&m', 'zara', 'uniqlo', 'decathlon',
    ],
    parentId: null,
    sortOrder: 4,
  },
  {
    id: 'cat_health',
    name: 'Health',
    icon: 'heart-pulse',
    color: categoryColors[5],
    type: 'expense',
    isCustom: false,
    keywords: [
      'pharmacy', 'hospital', 'doctor', 'medical', 'apollo',
      'medicine', 'clinic', 'lab', 'test', 'health', 'gym',
      'fitness', 'yoga', 'wellness', 'insurance', 'dental',
      'eye', 'optical', 'physio', 'therapy', 'netmeds', 'pharmeasy',
      'practo', '1mg', 'cult.fit', 'gold gym',
    ],
    parentId: null,
    sortOrder: 5,
  },
  {
    id: 'cat_entertainment',
    name: 'Entertainment',
    icon: 'film',
    color: categoryColors[6],
    type: 'expense',
    isCustom: false,
    keywords: [
      'netflix', 'spotify', 'movie', 'theatre', 'theater', 'gaming',
      'youtube', 'prime', 'hotstar', 'disney', 'jiocinema',
      'bookmyshow', 'pvr', 'inox', 'concert', 'event', 'music',
      'game', 'playstation', 'xbox', 'steam', 'apple tv',
      'hulu', 'hbo', 'sony liv', 'zee5',
    ],
    parentId: null,
    sortOrder: 6,
  },
  {
    id: 'cat_bills',
    name: 'Bills & Utilities',
    icon: 'receipt',
    color: categoryColors[7],
    type: 'expense',
    isCustom: false,
    keywords: [
      'jio', 'airtel', 'vi', 'vodafone', 'wifi', 'broadband',
      'internet', 'phone', 'mobile', 'recharge', 'postpaid',
      'prepaid', 'dth', 'tata sky', 'subscription', 'plan',
      'bill', 'utility', 'water', 't-mobile', 'at&t', 'verizon',
      'comcast', 'spectrum',
    ],
    parentId: null,
    sortOrder: 7,
  },
  {
    id: 'cat_education',
    name: 'Education',
    icon: 'graduation-cap',
    color: categoryColors[8],
    type: 'expense',
    isCustom: false,
    keywords: [
      'udemy', 'coursera', 'school', 'tuition', 'books',
      'college', 'university', 'course', 'class', 'coaching',
      'byju', 'unacademy', 'skillshare', 'linkedin learning',
      'edx', 'pluralsight', 'exam', 'fee', 'library', 'stationery',
    ],
    parentId: null,
    sortOrder: 8,
  },
  {
    id: 'cat_income',
    name: 'Income',
    icon: 'wallet',
    color: categoryColors[9],
    type: 'income',
    isCustom: false,
    keywords: [
      'salary', 'credited', 'received', 'refund', 'cashback',
      'interest', 'dividend', 'bonus', 'commission', 'freelance',
      'payment received', 'credit', 'income', 'payout', 'reward',
    ],
    parentId: null,
    sortOrder: 9,
  },
  {
    id: 'cat_transfer',
    name: 'Transfers',
    icon: 'arrow-right-left',
    color: categoryColors[10],
    type: 'both',
    isCustom: false,
    keywords: [
      'transferred', 'transfer', 'upi', 'neft', 'imps', 'rtgs',
      'sent to', 'paid to', 'bank transfer', 'wire', 'p2p',
      'zelle', 'venmo', 'cash app',
    ],
    parentId: null,
    sortOrder: 10,
  },
  {
    id: 'cat_uncategorized',
    name: 'Other',
    icon: 'circle-help',
    color: categoryColors[11],
    type: 'both',
    isCustom: false,
    keywords: [],
    parentId: null,
    sortOrder: 99,
  },
];
